[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install -r backend/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
